### ISSUE TITLE
Recommendation: Break package out

### ISSUE THREAD

**Issue by muschellij2** [lcrawlab/SINATRA#1]
Recommendation - break out the paper_results branch into a different repo (or the package itself into another repo).  Reason: 170mb .git folder (git history).  Mix of package + paper results.

**Comment by brwaang55** [comment]
That's a good recommendation! There's definitely some junk in there to prune, I've noticed that the package itself is ~300mb 😬

**Comment by muschellij2** [comment]
I have made a lot of changed and refactored a bit of stuff - I really liked the talk from @lorinanthony today, so hopefully this helps to push it over the line: https://github.com/muschellij2/SINATRA

**Comment by brwaang55** [comment]
That is so kind of you, thank you! We will work to merge the changes you made into our repo. I took a brief look at the changes, they have definitely made this package more usable and less clunky :).

**Comment by lorinanthony** [comment]
Thanks so much for doing this @muschellij2! This is incredible! @brwaang55 should we think about merging these edits (if John does not mind)? I agree this really cleaned the package.

**Comment by brwaang55** [comment]
@lorinanthony This can also be resolved, the paper results and working version of SINATRA for the AOAS paper is in [here](https://github.com/lcrawlab/SINATRA_AOAS_results). Please look there to have working scripts and tutorials.

**Comment by lorinanthony** [comment]
Awesome!
